package com.mycompany.car_rental.zouheir;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class BMW1 extends javax.swing.JFrame {

    /**
     * Creates new form BMW1
     */
    public BMW1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BMW = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListBMW = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NewCarAdd = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BMW.setMaximumSize(new java.awt.Dimension(580, 363));
        BMW.setMinimumSize(new java.awt.Dimension(580, 363));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("You Chose BMW :");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Please chose your car  :");

        ListBMW.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BMWM2", "BMWM3", "BMWM4", "BMWM5", "BMWM7", "BMWX1", "BMWX2", "BMWX5", "BMWix", " " }));
        ListBMW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListBMWActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Add A New Car");

        NewCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarAddActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BMWLayout = new javax.swing.GroupLayout(BMW);
        BMW.setLayout(BMWLayout);
        BMWLayout.setHorizontalGroup(
            BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BMWLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BMWLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BMWLayout.createSequentialGroup()
                        .addComponent(ListBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(BMWLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(BMWLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        BMWLayout.setVerticalGroup(
            BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BMWLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BMWLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListBMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BMW, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BMW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListBMWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListBMWActionPerformed
        // TODO add your handling code here:
        int index = ListBMW.getSelectedIndex();

        switch (index) {
            case 1 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission M2 = new FInalDecission();
                M2.setVisible(true);
                M2.price.setText("150");
                break;
            }
            case 2 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission X1 = new FInalDecission();
                X1.setVisible(true);
                X1.price.setText("200");
                break;

            }
            case 3 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission M4 = new FInalDecission();
                M4.setVisible(true);
                M4.price.setText("240");
                break;
            }
            case 4 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission M7 = new FInalDecission();
                M7.setVisible(true);
                M7.price.setText("180");
                break;

            }
            case 5 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission X2 = new FInalDecission();
                X2.setVisible(true);
                X2.price.setText("290");
                break;

            }
            case 6 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission M5 = new FInalDecission();
                M5.setVisible(true);
                M5.price.setText("300");
                break;

            }
            case 7 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission M3 = new FInalDecission();
                M3.setVisible(true);
                M3.price.setText("225");
                break;

            }
            case 8 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission X5 = new FInalDecission();
                X5.setVisible(true);
                X5.price.setText("200");
                break;

            }
            case 9 -> {
                BMW.setVisible(false);
                setVisible(false);
                FInalDecission iX = new FInalDecission();
                iX.setVisible(true);
                iX.price.setText("100");
                break;

            }
        }


    }//GEN-LAST:event_ListBMWActionPerformed

    private void NewCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarAddActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NewCarAddActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        // TODO add your handling code here:
        String nc = NewCarAdd.getText();
        ListBMW.addItem(nc);

    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BMW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BMW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BMW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BMW1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
BMW1 m = new BMW1();
m.setVisible(true);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BMW1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    public javax.swing.JPanel BMW;
    public javax.swing.JComboBox<String> ListBMW;
    public javax.swing.JTextField NewCarAdd;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
