/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental.zouheir;

/**
 *
 * @author user
 */
public class Honda extends javax.swing.JFrame {

    /**
     * Creates new form Honda
     */
    public Honda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Honda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListHonda = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NewCarAdd = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Honda.setMaximumSize(new java.awt.Dimension(580, 363));
        Honda.setMinimumSize(new java.awt.Dimension(580, 363));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("You Chose Honda :");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Please chose your car  :");

        ListHonda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HondaAccord", "HondaCRV", "HondaCivicSi", "HondaHRV", "HondaOdyssey", "HondaPassport", "HondaPilot", "HondaRidgeline", "TypeR", " " }));
        ListHonda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListHondaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Add A New Car");

        NewCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarAddActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout HondaLayout = new javax.swing.GroupLayout(Honda);
        Honda.setLayout(HondaLayout);
        HondaLayout.setHorizontalGroup(
            HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HondaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HondaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HondaLayout.createSequentialGroup()
                        .addComponent(ListHonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(HondaLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HondaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HondaLayout.setVerticalGroup(
            HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HondaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HondaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListHonda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Honda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Honda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListHondaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListHondaActionPerformed
        // TODO add your handling code here:
                                int index = ListHonda.getSelectedIndex();

         switch (index) {
             
                case 1 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission Accord = new FInalDecission();
                    Accord.setVisible(true);
                    Accord.price.setText("40");
                }
                case 2 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission CRV = new FInalDecission();
                    CRV.setVisible(true);
                    CRV.price.setText("55");
                }
                case 3 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission CivicSi = new FInalDecission();
                    CivicSi.setVisible(true);
                    CivicSi.price.setText("35");
                }
                case 4 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission HRV = new FInalDecission();
                    HRV.setVisible(true);
                    HRV.price.setText("80");
                }
                case 5 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission Odyssey = new FInalDecission();
                    Odyssey.setVisible(true);
                    Odyssey.price.setText("100");
                }
                case 6 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission Passport = new FInalDecission();
                    Passport.setVisible(true);
                    Passport.price.setText("130");
                }
                case 7 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission Pilot = new FInalDecission();
                    Pilot.setVisible(true);
                    Pilot.price.setText("136");
                }
                case 8 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission Ridgeline = new FInalDecission();
                    Ridgeline.setVisible(true);
                    Ridgeline.price.setText("15");
                }
                case 9 -> {
                    Honda.setVisible(false);
                    setVisible(false);
                    FInalDecission R = new FInalDecission();
                    R.setVisible(true);
                    R.price.setText("100");
                }
            }
        
    }//GEN-LAST:event_ListHondaActionPerformed

    private void NewCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarAddActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_NewCarAddActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        // TODO add your handling code here:
        String nc=NewCarAdd.getText();
        ListHonda.addItem(nc);

    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Honda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Honda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Honda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Honda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Honda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    public javax.swing.JPanel Honda;
    private javax.swing.JComboBox<String> ListHonda;
    public javax.swing.JTextField NewCarAdd;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
