/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental.zouheir;

/**
 *
 * @author user
 */
public class Hyundai extends javax.swing.JFrame {

    /**
     * Creates new form Hyundai
     */
    public Hyundai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Hyundai = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ListHyundai = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NewCarAdd = new javax.swing.JTextField();
        Add = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Hyundai.setBackground(new java.awt.Color(0, 51, 102));
        Hyundai.setMaximumSize(new java.awt.Dimension(580, 363));
        Hyundai.setMinimumSize(new java.awt.Dimension(580, 363));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("Please chose your car  :");

        ListHyundai.setBackground(new java.awt.Color(255, 153, 51));
        ListHyundai.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ListHyundai.setForeground(new java.awt.Color(255, 255, 255));
        ListHyundai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HyundaiElantra", "HyundaiIONIQ5", "HyundaiIONIQ6", "HyundaiKona", "HyundaiPalisade", "HyundaiSantafe", "HyundaiSonata", "HyundaiTucson", "HyundaiVenue", " ", " ", " ", " " }));
        ListHyundai.setBorder(null);
        ListHyundai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListHyundaiActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Add A New Car");

        NewCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarAddActionPerformed(evt);
            }
        });

        Add.setBackground(new java.awt.Color(255, 153, 0));
        Add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Add.setForeground(new java.awt.Color(255, 255, 255));
        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("You Chose Hyundai:");

        javax.swing.GroupLayout HyundaiLayout = new javax.swing.GroupLayout(Hyundai);
        Hyundai.setLayout(HyundaiLayout);
        HyundaiLayout.setHorizontalGroup(
            HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HyundaiLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HyundaiLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HyundaiLayout.createSequentialGroup()
                        .addComponent(ListHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(HyundaiLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(HyundaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        HyundaiLayout.setVerticalGroup(
            HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HyundaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HyundaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListHyundai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hyundai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hyundai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListHyundaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListHyundaiActionPerformed
        // TODO add your handling code here:
                        int index = ListHyundai.getSelectedIndex();

          switch (index) {
                case 1 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Elantra = new FInalDecission();
                    Elantra.setVisible(true);
                    Elantra.price.setText("60");
                }
                case 2 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission IONIQ5 = new FInalDecission();
                    IONIQ5.setVisible(true);
                    IONIQ5.price.setText("65");
                }
                case 3 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission IONIQ6 = new FInalDecission();
                    IONIQ6.setVisible(true);
                    IONIQ6.price.setText("39");
                }
                case 4 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Kona = new FInalDecission();
                    Kona.setVisible(true);
                    Kona.price.setText("70");
                }
                case 5 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Palisade = new FInalDecission();
                    Palisade.setVisible(true);
                    Palisade.price.setText("78");
                }
                case 6 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission SantaFe = new FInalDecission();
                    SantaFe.setVisible(true);
                    SantaFe.price.setText("90");
                }
                case 7 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Sonata = new FInalDecission();
                    Sonata.setVisible(true);
                    Sonata.price.setText("10");
                }
                case 8 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Tucson = new FInalDecission();
                    Tucson.setVisible(true);
                    Tucson.price.setText("15");
                }
                case 9 -> {
                    Hyundai.setVisible(false);
                    setVisible(false);
                    FInalDecission Venue = new FInalDecission();
                    Venue.setVisible(true);
                    Venue.price.setText("100");
                }
            }
    }//GEN-LAST:event_ListHyundaiActionPerformed

    private void NewCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCarAddActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        // TODO add your handling code here:
        String nc=NewCarAdd.getText();
        ListHyundai.addItem(nc);
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hyundai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hyundai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hyundai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hyundai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hyundai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    public javax.swing.JPanel Hyundai;
    private javax.swing.JComboBox<String> ListHyundai;
    public javax.swing.JTextField NewCarAdd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
