/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.car_rental.zouheir;

/**
 *
 * @author user
 */
public class Mercedes1 extends javax.swing.JFrame {

    /**
     * Creates new form Mercedes1
     */
    public Mercedes1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Mercedes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListMercedes = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NewCarAdd = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Mercedes.setMaximumSize(new java.awt.Dimension(580, 363));
        Mercedes.setMinimumSize(new java.awt.Dimension(580, 363));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("You Chose Mercedes :");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Please chose your car  :");

        ListMercedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MercedesCLA", "MercedesCLS", "MercedesCLE", "MercedesEQA", "MercedesEQS", "MercedesEQG", "MercedesGLA", "MercedesGLB", "MercedesGLS", " ", " " }));
        ListMercedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListMercedesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Add A New Car");

        NewCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarAddActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MercedesLayout = new javax.swing.GroupLayout(Mercedes);
        Mercedes.setLayout(MercedesLayout);
        MercedesLayout.setHorizontalGroup(
            MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MercedesLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MercedesLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MercedesLayout.createSequentialGroup()
                        .addComponent(ListMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(MercedesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(MercedesLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MercedesLayout.setVerticalGroup(
            MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MercedesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MercedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListMercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mercedes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Mercedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListMercedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListMercedesActionPerformed
        // TODO add your handling code here:
            int index = ListMercedes.getSelectedIndex();

           switch (index) {
                case 1 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission CLA = new FInalDecission();
                    CLA.setVisible(true);
                    CLA.price.setText("150");
                }
                case 2 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission CLS = new FInalDecission();
                    CLS.setVisible(true);
                    CLS.price.setText("280");
                }
                case 3 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission CLE = new FInalDecission();
                    CLE.setVisible(true);
                    CLE.price.setText("260");
                }
                case 4 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission EQA = new FInalDecission();
                    EQA.setVisible(true);
                    EQA.price.setText("140");
                }
                case 5 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission EQS = new FInalDecission();
                    EQS.setVisible(true);
                    EQS.price.setText("110");
                }
                case 6 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission EQG = new FInalDecission();
                    EQG.setVisible(true);
                    EQG.price.setText("90");
                }
                case  7 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission GLA = new FInalDecission();
                    GLA.setVisible(true);
                    GLA.price.setText("325");
                }
                case 8 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission GLB = new FInalDecission();
                    GLB.setVisible(true);
                    GLB.price.setText("275");
                }
                case 9 -> {
                    Mercedes.setVisible(false);
                    setVisible(false);
                    FInalDecission GLS = new FInalDecission();
                    GLS.setVisible(true);
                    GLS.price.setText("110");
                }
            }
    }//GEN-LAST:event_ListMercedesActionPerformed

    private void NewCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewCarAddActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed

        // TODO add your handling code here:
        String nc=NewCarAdd.getText();
        ListMercedes.addItem(nc);
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mercedes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mercedes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mercedes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mercedes1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mercedes1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    private javax.swing.JComboBox<String> ListMercedes;
    public javax.swing.JPanel Mercedes;
    public javax.swing.JTextField NewCarAdd;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
