package com.mycompany.car_rental.zouheir;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Toyota1 extends javax.swing.JFrame {

    /**
     * Creates new form Toyota1
     */
    public Toyota1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Toyota = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListToyota = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        NewCarAdd = new javax.swing.JTextField();
        Add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Toyota.setMaximumSize(new java.awt.Dimension(580, 363));
        Toyota.setMinimumSize(new java.awt.Dimension(580, 363));
        Toyota.setPreferredSize(new java.awt.Dimension(580, 363));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("You Chose Toyota :");
        jLabel1.setToolTipText("");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Please chose your car  :");

        ListToyota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ToyotaCorolla", "ToyotaCamry", "ToyotaPrius", "ToyotaGTR", "ToyotaCrown", "ToyotaMirai", "ToyotaCHR", "ToyotaRav4", "Toyota4Runner", " " }));
        ListToyota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListToyotaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Add A New Car");

        NewCarAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCarAddActionPerformed(evt);
            }
        });

        Add.setText("Add");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ToyotaLayout = new javax.swing.GroupLayout(Toyota);
        Toyota.setLayout(ToyotaLayout);
        ToyotaLayout.setHorizontalGroup(
            ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToyotaLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToyotaLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToyotaLayout.createSequentialGroup()
                        .addComponent(ListToyota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83))))
            .addGroup(ToyotaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ToyotaLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(Add)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ToyotaLayout.setVerticalGroup(
            ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToyotaLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addGroup(ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ToyotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ListToyota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewCarAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(Add)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toyota, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Toyota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListToyotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListToyotaActionPerformed
        // TODO add your handling code here:
                int index = ListToyota.getSelectedIndex();

        switch (index) {
                case 1 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Corolla = new FInalDecission();
                    Corolla.setVisible(true);
                    Corolla.price.setText("40");
                }
                case 2 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Camry = new FInalDecission();
                    Camry.setVisible(true);
                    Camry.price.setText("55");
                }
                case 3 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Prius = new FInalDecission();
                    Prius.setVisible(true);
                    Prius.price.setText("35");
                }
                case 4 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission GTR = new FInalDecission();
                    GTR.setVisible(true);
                    GTR.price.setText("80");
                }
                case 5 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Crown = new FInalDecission();
                    Crown.setVisible(true);
                    Crown.price.setText("100");
                }
                case 6 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Mirai = new FInalDecission();
                    Mirai.setVisible(true);
                    Mirai.price.setText("130");
                }
                case 7 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission CHR = new FInalDecission();
                    CHR.setVisible(true);
                    CHR.price.setText("136");
                }
                case 8 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Rav4  = new FInalDecission();
                    Rav4.setVisible(true);
                    Rav4.price.setText("15");
                }
                case 9 -> {
                    Toyota.setVisible(false);
                    setVisible(false);
                    FInalDecission Runner  = new FInalDecission();
                    Runner.setVisible(true);
                    Runner.price.setText("100");
                }
            }
    }//GEN-LAST:event_ListToyotaActionPerformed

    private void NewCarAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCarAddActionPerformed
        // TODO add your handling code here:
   
        
        
    }//GEN-LAST:event_NewCarAddActionPerformed

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
   
        // TODO add your handling code here:
             String nc=NewCarAdd.getText();
               ListToyota.addItem(nc);

        
        
    }//GEN-LAST:event_AddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Toyota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Toyota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Toyota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Toyota1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Toyota1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Add;
    private javax.swing.JComboBox<String> ListToyota;
    public javax.swing.JTextField NewCarAdd;
    public javax.swing.JPanel Toyota;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
